### PR TITLE
Modified to use boto3 in order to support Amazons new multi availability zone reserved instances. 

### LINKED ISSUE #3: Reserved Instance of regional scope not identified as used
The recent reserved instances I have purchased have a scope of "region" instead of "availability zone" it seems that these are not matched with running instances, so the covered instances are showing as "not reserved".

Here is the output from the CLI which describes one of these instances. Note that there is no availability zone.
```
 {
            "ReservedInstancesId": "REMOVED",
            "OfferingType": "Partial Upfront",
            "FixedPrice": 1820.0,
            "End": "2018-02-10T13:19:54.000Z",
            "ProductDescription": "Linux/UNIX",
            "Scope": "Region",
            "UsagePrice": 0.0,
            "RecurringCharges": [
                {
                    "Amount": 0.155,
                    "Frequency": "Hourly"
                }
            ],
            "OfferingClass": "standard",
            "Start": "2017-02-10T13:19:55.193Z",
            "State": "active",
            "InstanceCount": 1,
            "CurrencyCode": "USD",
            "Duration": 31536000,
            "InstanceTenancy": "default",
            "InstanceType": "i2.xlarge"
        }
```

### PR DESCRIPTION
**Pull request by sjafferali**
Fixes #3

### CODE REVIEW

**Comment by AgDude** [comment]
Thanks for submitting. From a glance at the source, it looks like this is only checking reserved instances against the region. This script will need to determine which instances are for an entire region and which are AZ only. There are lot's of existing reserved instances which are only for a single AZ.

**Comment by sjafferali** [comment]
Not sure if it is really worth supporting as Amazon does not sell reserved instances locked to a single availability zone anymore. I just found it easier to modify all my reserved instances to multi availability zone instances since there was no downside to making the switch other than providing additional flexibility with the instances.

**Comment by AgDude** [comment]
I didn't realize AWS offered free conversion of existing reserved instances. If that is the case I would agree with you. This project just needs to be clear that it is a breaking change.

In that case tests and readme need to be updated, and the changes are probably fine.

@adamstauffer are you still maintaining this project, and are you open to this change?

**Comment by adamstauffer** [comment]
AWS does still offer RIs with a specific AZ; when on the "Purchase Reserved Instances" screen, select the checkbox at the upper right "Only show offerings that reserve capacity". However, like @sjafferali said, there doesn't seem to be any cost difference associated with these reserve capacity RIs vs. regional benefit RIs.

I'm sure there's a way we could support both organizations that will still buy reserve capacity RIs and those that will buy the new regional benefit RIs. I want to think about this a little more before releasing any compatibility breaking versions. I'm going to play around with this a bit this weekend and see if I can get something that will work for everyone. If not, I can update the README and try to get the tests working again with these new changes

**Comment by adamstauffer** [comment]
Can you give the latest version (0.0.4) a shot? I tested on an account with regular RIs, all regional benefit RIs and a mix of both. Let me know if this works for you all

**Comment by AgDude** [comment]
Works for me. Thanks for the update.

**Comment by adamstauffer** [comment]
OK, going to close this then. Thanks to you both!

**Comment by mbassett** [comment]
The difference is that  multi-region reservations do not actually reserve capacity.  Good luck come December if you're only using those.

**Pull request closed without merging**
